-- Archived none-ls config.
-- This file is intentionally comment-only so discharged configs stay inert.
-- Active replacements:
-- - formatting: after/plugin/lsp/conform.lua
-- - linting: after/plugin/lsp/lint.lua
--
-- Previous none-ls setup handled:
-- - stylua
-- - shfmt
-- - google-java-format
-- - shellcheck
-- - luacheck
