-- Go DAP adapter (Delve)
-- To restore: uncomment and add to after/plugin/lsp/dap.lua
--
-- dap.adapters.delve = {
--     type = "server",
--     port = "${port}",
--     executable = {
--         command = "dlv",
--         args = { "dap", "-l", "127.0.0.1:${port}" },
--     },
-- }
-- dap.configurations.go = {
--     {
--         type = "delve",
--         name = "Debug",
--         request = "launch",
--         program = "${file}",
--     },
--     {
--         type = "delve",
--         name = "Debug test",
--         request = "launch",
--         mode = "test",
--         program = "${file}",
--     },
-- }
