name: "Master CI"

on:
  workflow_call:

# Set default permissions for all jobs
permissions:
  contents: read
  packages: read
  security-events: write

concurrency:
  group: master-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    if: false # Disable this job
    uses: ./.github/workflows/setup-environment-macos.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true

  neovim-tests:
    if: false # Disable this job
    needs: setup
    uses: ./.github/workflows/macos-neovim-tests.yml
    with: {}
