name: "Master CI"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
    - cron: "33 12 * * 1"

# Set default permissions for all jobs
permissions:
  contents: read
  packages: read
  security-events: write

concurrency:
  group: master-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-tests:
    uses: ./.github/workflows/macos-neovim-tests.yml

  windows-tests:
    uses: ./.github/workflows/pr-windows-tests.yml
