name: Neovim CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Cache Homebrew packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOMEBREW_CACHE }}
            ${{ env.HOMEBREW_PREFIX }}
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/packages.sh') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/packages.sh') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/packages.sh') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up cache directories
        run: |
          mkdir -p $HOME/.cache/pip
          mkdir -p $HOME/.npm
          echo "PIP_CACHE_DIR=$HOME/.cache/pip" >> $GITHUB_ENV
          echo "NPM_CACHE_DIR=$HOME/.npm" >> $GITHUB_ENV
          echo "HOMEBREW_CACHE=$HOME/Library/Caches/Homebrew" >> $GITHUB_ENV
          echo "HOMEBREW_PREFIX=/usr/local/Homebrew" >> $GITHUB_ENV

      - name: Install Neovim
        run: brew install neovim

      - name: Set up Python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f infra/install.sh ]; then
            chmod +x infra/install.sh
            source .venv/bin/activate
            CI=true ./infra/install.sh
          fi

      - name: Run sanity tests
        run: |
          chmod +x test/setup/sanity_nvim_start.sh
          source .venv/bin/activate
          ./test/setup/sanity_nvim_start.sh 