name: "Master CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "33 12 * * 1"

# Set default permissions for all jobs
permissions:
  contents: read
  packages: read
  security-events: write

jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true

  neovim-tests:
    needs: setup
    uses: ./.github/workflows/neovim-tests.yml
