name: Build and Publish Docker Image

on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker.yml"
      - "infra/**"
      - "lua/**"
      - "after/**"
  pull_request:
    branches: [master]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker.yml"
      - "infra/**"
      - "lua/**"
      - "after/**"
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@373ed2c4e77da2dc39949dce723c6a8e4d5a6b25
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.3
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f7875263e6086d7de6f70d76e3d88
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@4f7e0a084d0c75964e3e0f4c48460d32c3441b8e
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
