name: "Lua Analysis"

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '33 12 * * 1'

jobs:
  analyze:
    name: Analyze Lua
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if tests should run (test/, infra/, *.lua)
      id: test_check
      run: |
        chmod +x infra/should_run_tests.sh
        if bash infra/should_run_tests.sh ${{ github.base_ref }} ${{ github.sha }}; then
          echo "run_tests=true" >> $GITHUB_OUTPUT
        else
          echo "run_tests=false" >> $GITHUB_OUTPUT
        fi

    - name: Skip if no test/infra/.lua changes
      if: steps.test_check.outputs.run_tests == 'false'
      run: |
        echo "No test/infra/.lua changes. Skipping tests."
        exit 0

    - name: Install Lua and LuaRocks
      if: steps.test_check.outputs.run_tests == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4 luarocks

    - name: Install luacheck
      if: steps.test_check.outputs.run_tests == 'true'
      run: |
        sudo luarocks install luacheck

    - name: Run luacheck
      if: steps.test_check.outputs.run_tests == 'true'
      run: |
        luacheck lua/ after/plugin/ --codes --ranges --formatter plain 