name: "Neovim Tests"

permissions:
  contents: read

on:
  workflow_call:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "33 12 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    name: Check for Changes
    runs-on: macos-latest
    outputs:
      run_tests: ${{ steps.test_check.outputs.run_tests }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check if tests should run (test/, infra/, *.lua)
        id: test_check
        run: |
          chmod +x infra/should_run_tests.sh || true
          bash infra/should_run_tests.sh ${{ github.base_ref }} ${{ github.sha }} || exit_code=$?
          case ${exit_code:-0} in
            0)
              echo "run_tests=true" >> $GITHUB_OUTPUT
              ;;
            1)
              echo "run_tests=false" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Unexpected error occurred (exit code: ${exit_code:-0}). Running tests to be safe."
              echo "run_tests=true" >> $GITHUB_OUTPUT
              ;;
          esac

  setup:
    name: Setup Environment
    needs: check-changes
    if: needs.check-changes.outputs.run_tests == 'true'
    uses: ./.github/workflows/setup-environment.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true
      runner: macos-latest

  test:
    name: Run Tests
    needs: [check-changes, setup]
    if: needs.check-changes.outputs.run_tests == 'true'
    uses: ./.github/workflows/test-steps.yml
    with:
      platform: macos
      venv_path: ${{ needs.setup.outputs.virtual_env }}
      use_cache: true
      install_deps: true
