name: "PR macOS Tests"

permissions:
  contents: read

on:
  workflow_call:
  pull_request:
    branches: ["master"]
    paths:
      - "infra/**"
      - ".github/workflows/**"
      - "lua/**"
      - "after/**"
      - "init.lua"
      - "lazy-lock.json"

concurrency:
  group: pr-macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/macos-neovim-tests.yml
