name: "PR macOS Tests"

on:
  pull_request:
    branches: ["master"]

jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true
      runner: macos-latest

  test:
    needs: setup
    uses: ./.github/workflows/test-steps.yml
    with:
      platform: macos
      venv_path: ${{ needs.setup.outputs.virtual_env }}
      use_cache: true
      install_deps: true
