name: "PR macOS Tests"

on:
  pull_request:
    branches: ["master"]

jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true

  macos-test:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g neovim
          cargo install stylua

      - name: Run basic Neovim tests
        run: |
          nvim --headless -c "lua require('test.core')" -c "quit"

      - name: Run LSP tests
        run: |
          nvim --headless -c "lua require('test.lsp')" -c "quit"

      - name: Run Treesitter tests
        run: |
          nvim --headless -c "lua require('test.treesitter')" -c "quit"

      - name: Check formatting
        run: |
          stylua --check lua/
          stylua --check after/plugin/

      - name: Run performance tests
        run: |
          nvim --headless -c "lua require('test.performance')" -c "quit"
