name: "PR Windows Tests"

on:
  pull_request:
    branches: ["master"]

jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml
    with:
      setup_python: true
      setup_rust: true
      setup_node: true
      setup_lua: true
      runner: windows-latest

  windows-test:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: .venv

      - name: Run basic Neovim tests
        shell: bash
        run: |
          source "$GITHUB_WORKSPACE/.venv/Scripts/activate"
          nvim --headless -c "lua require('test.core')" -c "quit"

      - name: Run LSP tests
        shell: bash
        run: |
          source "$GITHUB_WORKSPACE/.venv/Scripts/activate"
          nvim --headless -c "lua require('test.lsp')" -c "quit"

      - name: Run Treesitter tests
        shell: bash
        run: |
          source "$GITHUB_WORKSPACE/.venv/Scripts/activate"
          nvim --headless -c "lua require('test.treesitter')" -c "quit"

      - name: Check formatting
        shell: bash
        run: |
          source "$GITHUB_WORKSPACE/.venv/Scripts/activate"
          stylua --check lua/
          stylua --check after/plugin/
