name: Setup Windows Environment

on:
  workflow_call:
    inputs:
      setup_python:
        required: true
        type: boolean
        default: true
      setup_rust:
        required: true
        type: boolean
        default: true
      setup_node:
        required: true
        type: boolean
        default: true
      setup_lua:
        required: true
        type: boolean
        default: true
    outputs:
      virtual_env:
        description: "Path to virtual environment"
        value: ${{ jobs.setup-environment.outputs.virtual_env }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: windows-latest
    outputs:
      virtual_env: ${{ steps.venv-win.outputs.virtual_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Chocolatey packages
        uses: actions/cache@v4
        with:
          path: |
            C:\ProgramData\chocolatey\lib
            C:\ProgramData\chocolatey\bin
            C:\tools
            C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-${{ runner.arch }}-choco-${{ hashFiles('infra/packages/*.ps1', 'infra/packages/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-choco-

      - name: Set up Node.js
        if: inputs.setup_node
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Cache npm packages
        if: inputs.setup_node
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ runner.arch }}

      - name: Log Rust cache info
        if: inputs.setup_rust
        shell: pwsh
        run: |
          Write-Output "=== Rust Cache Info ==="
          Write-Output "Cache paths:"
          Write-Output "- $env:USERPROFILE\.cargo"
          Write-Output "- $env:USERPROFILE\.rustup"
          Write-Output "Cache key: ${{ runner.os }}-${{ runner.arch }}-rust-${{ hashFiles('infra/packages/cargo.sh', 'infra/packages/cargo.ps1') }}"
          Write-Output "========================="

      - name: Cache Rust
        if: inputs.setup_rust
        uses: actions/cache@v4
        id: rust-cache
        with:
          path: |
            ${{ runner.os == 'Windows' && format('{0}\\.cargo', env.USERPROFILE) || '~/.cargo' }}
            ${{ runner.os == 'Windows' && format('{0}\\.rustup', env.USERPROFILE) || '~/.rustup' }}
          key: ${{ runner.os }}-${{ runner.arch }}-rust-${{ hashFiles('infra/packages/cargo.sh', 'infra/packages/cargo.ps1') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-rust-

      - name: Log Rust cache result
        if: inputs.setup_rust
        shell: pwsh
        run: |
          Write-Output "=== Rust Cache Result ==="
          Write-Output "Cache hit: ${{ steps.rust-cache.outputs.cache-hit }}"
          Write-Output "Cache sizes:"
          if (Test-Path "$env:USERPROFILE\.cargo") {
              Get-ChildItem "$env:USERPROFILE\.cargo" -Recurse | Measure-Object -Property Length -Sum | Select-Object @{Name="Size(MB)";Expression={"{0:N2}" -f ($_.Sum / 1MB)}}
          }
          if (Test-Path "$env:USERPROFILE\.rustup") {
              Get-ChildItem "$env:USERPROFILE\.rustup" -Recurse | Measure-Object -Property Length -Sum | Select-Object @{Name="Size(MB)";Expression={"{0:N2}" -f ($_.Sum / 1MB)}}
          }
          Write-Output "==========================="

      - name: Log Visual Studio Build Tools cache info
        shell: pwsh
        run: |
          Write-Output "=== Visual Studio Build Tools Cache Info ==="
          Write-Output "Cache paths:"
          Write-Output "- $env:USERPROFILE\vs_buildtools"
          Write-Output "Cache key: ${{ runner.os }}-${{ runner.arch }}-vstools-${{ hashFiles('infra/packages/vs-setup.ps1') }}"
          Write-Output "========================="

      - name: Cache Visual Studio Build Tools
        uses: actions/cache@v4
        id: vstools-cache
        with:
          path: ${{ runner.os == 'Windows' && format('{0}\\vs_buildtools', env.USERPROFILE) || '~/vs_buildtools' }}
          key: ${{ runner.os }}-${{ runner.arch }}-vstools-${{ hashFiles('infra/packages/vs-setup.ps1') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-vstools-

      - name: Log Visual Studio Build Tools cache result
        shell: pwsh
        run: |
          Write-Output "=== Visual Studio Build Tools Cache Result ==="
          Write-Output "Cache hit: ${{ steps.vstools-cache.outputs.cache-hit }}"
          Write-Output "Cache size:"
          if (Test-Path "$env:USERPROFILE\vs_buildtools") {
              Get-ChildItem "$env:USERPROFILE\vs_buildtools" -Recurse | Measure-Object -Property Length -Sum | Select-Object @{Name="Size(MB)";Expression={"{0:N2}" -f ($_.Sum / 1MB)}}
          }
          Write-Output "==========================="

      - name: Set up Python
        if: inputs.setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache virtual environment
        if: inputs.setup_python
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: ${{ runner.tool_cache }}/venv
          key: ${{ runner.os }}-${{ runner.arch }}-venv-${{ hashFiles('infra/packages/pip.sh', 'infra/packages/pip.ps1') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-venv-

      - name: Set up Python virtual environment
        if: inputs.setup_python
        id: venv-win
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          # Use runner.tool_cache for consistent path
          $venvPath = Join-Path $env:RUNNER_TOOL_CACHE "venv"
          Write-Output "Setting up virtual environment at: $venvPath"

          # Create parent directory if it doesn't exist
          $parentDir = Split-Path -Parent $venvPath
          if (-not (Test-Path $parentDir)) {
              Write-Output "Creating parent directory: $parentDir"
              New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
          }

          # Check if virtual environment exists in cache
          if (Test-Path $venvPath) {
              Write-Output "Found existing virtual environment in cache"
              # Verify the activation script exists
              $activateScript = Join-Path $venvPath "Scripts\Activate.ps1"
              if (-not (Test-Path $activateScript)) {
                  Write-Output "Activation script not found, recreating virtual environment..."
                  Remove-Item -Path $venvPath -Recurse -Force
                  Start-Sleep -Seconds 2
              }
          }

          # Create new virtual environment if needed
          if (-not (Test-Path $venvPath)) {
              Write-Output "Creating new virtual environment..."
              python -m venv $venvPath
              if ($LASTEXITCODE -ne 0) {
                  Write-Error "Failed to create virtual environment"
                  Write-Output "Python version: $(python --version)"
                  Write-Output "Python path: $(Get-Command python | Select-Object -ExpandProperty Source)"
                  Write-Output "Current directory: $(Get-Location)"
                  Write-Output "Directory contents:"
                  Get-ChildItem
                  exit 1
              }
          }

          # Set the output variable
          Write-Output "virtual_env=$venvPath" >> $env:GITHUB_OUTPUT
          Write-Output "Setting virtual_env output to: $venvPath"

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Starting Visual Studio Build Tools installation process..."

          # Create installation directory
          $vsInstallPath = Join-Path $env:USERPROFILE "vs_buildtools"
          if (-not (Test-Path $vsInstallPath)) {
              New-Item -ItemType Directory -Path $vsInstallPath -Force | Out-Null
          }

          # Download VS Build Tools installer
          $vsInstallerUrl = "https://aka.ms/vs/16/release/vs_buildtools.exe"
          $vsInstallerPath = "$env:TEMP\vs_buildtools.exe"

          Write-Output "Downloading VS Build Tools installer..."
          Invoke-WebRequest -Uri $vsInstallerUrl -OutFile $vsInstallerPath -UseBasicParsing

          # Install VS Build Tools
          Write-Output "Installing VS Build Tools..."
          $process = Start-Process -FilePath $vsInstallerPath -ArgumentList @(
              "--quiet",
              "--wait",
              "--norestart",
              "--nocache",
              "--installPath", $vsInstallPath,
              "--add", "Microsoft.VisualStudio.Workload.VCTools",
              "--includeRecommended"
          ) -Wait -PassThru

          if ($process.ExitCode -ne 0) {
              throw "Failed to install Visual Studio Build Tools. Exit code: $($process.ExitCode)"
          }

          # Verify installation
          $vsDevCmd = Join-Path $vsInstallPath "Common7\Tools\VsDevCmd.bat"
          if (-not (Test-Path $vsDevCmd)) {
              throw "VsDevCmd.bat not found after installation"
          }

          Write-Output "Visual Studio Build Tools installed successfully"

      - name: Set up Visual Studio environment
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $vsPath = Join-Path $env:USERPROFILE "vs_buildtools"
          $vsDevCmd = Join-Path $vsPath "Common7\Tools\VsDevCmd.bat"

          if (-not (Test-Path $vsDevCmd)) {
              throw "VsDevCmd.bat not found at: $vsDevCmd"
          }

          Write-Output "Setting up Visual Studio environment..."
          cmd /c "`"$vsDevCmd`" && set" | ForEach-Object {
              if ($_ -match "^(.*?)=(.*)$") {
                  $name = $matches[1]
                  $value = $matches[2]
                  [System.Environment]::SetEnvironmentVariable($name, $value, [System.EnvironmentVariableTarget]::Process)
              }
          }

          # Verify setup
          $clPath = (Get-Command cl.exe -ErrorAction SilentlyContinue).Source
          if (-not $clPath) {
              throw "Failed to set up Visual Studio environment. cl.exe not found."
          }
          Write-Output "Visual Studio environment set up successfully"

      - name: Install system packages
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing system packages..."
          choco install neovim -y
          choco install luarocks -y

      - name: Install Node.js packages
        if: inputs.setup_node
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing Node.js packages..."
          npm install -g neovim

      - name: Install Rust
        if: inputs.setup_rust
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing Rust..."
          Invoke-WebRequest -Uri https://win.rustup.rs -OutFile rustup-init.exe
          .\rustup-init.exe -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          rustup default stable
          cargo install stylua
