name: Setup Windows Environment

on:
  workflow_call:
    inputs:
      setup_python:
        required: true
        type: boolean
        default: true
      setup_rust:
        required: true
        type: boolean
        default: true
      setup_node:
        required: true
        type: boolean
        default: true
      setup_lua:
        required: true
        type: boolean
        default: true
    outputs:
      virtual_env:
        description: "Path to virtual environment"
        value: ${{ jobs.setup-environment.outputs.virtual_env }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: windows-latest
    outputs:
      virtual_env: ${{ steps.venv-win.outputs.virtual_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Chocolatey packages
        uses: actions/cache@v4
        with:
          path: |
            C:\ProgramData\chocolatey\lib
            C:\ProgramData\chocolatey\bin
            C:\tools
            C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-${{ runner.arch }}-choco-${{ hashFiles('infra/packages/*.ps1', 'infra/packages/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-choco-

      - name: Set up Node.js
        if: inputs.setup_node
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Cache npm packages
        if: inputs.setup_node
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ runner.arch }}

      - name: Set up Python
        if: inputs.setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Starting Visual Studio Build Tools installation process..."

          # Create installation directory
          $vsInstallPath = Join-Path $env:USERPROFILE "vs_buildtools"
          if (-not (Test-Path $vsInstallPath)) {
              New-Item -ItemType Directory -Path $vsInstallPath -Force | Out-Null
          }

          # Download VS Build Tools installer
          $vsInstallerUrl = "https://aka.ms/vs/16/release/vs_buildtools.exe"
          $vsInstallerPath = "$env:TEMP\vs_buildtools.exe"

          Write-Output "Downloading VS Build Tools installer..."
          Invoke-WebRequest -Uri $vsInstallerUrl -OutFile $vsInstallerPath -UseBasicParsing

          # Install VS Build Tools
          Write-Output "Installing VS Build Tools..."
          $process = Start-Process -FilePath $vsInstallerPath -ArgumentList @(
              "--quiet",
              "--wait",
              "--norestart",
              "--nocache",
              "--installPath", $vsInstallPath,
              "--add", "Microsoft.VisualStudio.Workload.VCTools",
              "--includeRecommended"
          ) -Wait -PassThru

          if ($process.ExitCode -ne 0) {
              throw "Failed to install Visual Studio Build Tools. Exit code: $($process.ExitCode)"
          }

          # Verify installation
          $vsDevCmd = Join-Path $vsInstallPath "Common7\Tools\VsDevCmd.bat"
          if (-not (Test-Path $vsDevCmd)) {
              throw "VsDevCmd.bat not found after installation"
          }

          Write-Output "Visual Studio Build Tools installed successfully"

      - name: Set up Visual Studio environment
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $vsPath = Join-Path $env:USERPROFILE "vs_buildtools"
          $vsDevCmd = Join-Path $vsPath "Common7\Tools\VsDevCmd.bat"

          if (-not (Test-Path $vsDevCmd)) {
              throw "VsDevCmd.bat not found at: $vsDevCmd"
          }

          Write-Output "Setting up Visual Studio environment..."
          cmd /c "`"$vsDevCmd`" && set" | ForEach-Object {
              if ($_ -match "^(.*?)=(.*)$") {
                  $name = $matches[1]
                  $value = $matches[2]
                  [System.Environment]::SetEnvironmentVariable($name, $value, [System.EnvironmentVariableTarget]::Process)
              }
          }

          # Verify setup
          $clPath = (Get-Command cl.exe -ErrorAction SilentlyContinue).Source
          if (-not $clPath) {
              throw "Failed to set up Visual Studio environment. cl.exe not found."
          }
          Write-Output "Visual Studio environment set up successfully"

      - name: Install system packages
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing system packages..."
          choco install neovim -y
          choco install luarocks -y

      - name: Cache virtual environment
        if: inputs.setup_python
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: ${{ runner.tool_cache }}/venv
          key: ${{ runner.os }}-${{ runner.arch }}-venv-${{ hashFiles('infra/packages/pip.sh', 'infra/packages/pip.ps1') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-venv-

      - name: Set up Python virtual environment
        if: inputs.setup_python
        id: venv-win
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          # Use RUNNER_TEMP for more reliable path
          $venvPath = Join-Path $env:RUNNER_TEMP "venv"
          Write-Output "Setting up virtual environment at: $venvPath"

          # Create parent directory if it doesn't exist
          $parentDir = Split-Path -Parent $venvPath
          if (-not (Test-Path $parentDir)) {
              Write-Output "Creating parent directory: $parentDir"
              New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
          }

          # Remove existing virtual environment if it exists
          if (Test-Path $venvPath) {
              Write-Output "Removing existing virtual environment..."
              Remove-Item -Path $venvPath -Recurse -Force
              Start-Sleep -Seconds 2
          }

          # Create virtual environment
          Write-Output "Creating virtual environment..."
          python -m venv $venvPath
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create virtual environment"
              Write-Output "Python version: $(python --version)"
              Write-Output "Python path: $(Get-Command python | Select-Object -ExpandProperty Source)"
              Write-Output "Current directory: $(Get-Location)"
              Write-Output "Directory contents:"
              Get-ChildItem
              exit 1
          }

          # Verify virtual environment
          if (-not (Test-Path $venvPath)) {
              Write-Error "Virtual environment directory not found after creation"
              Write-Output "Current directory: $(Get-Location)"
              Write-Output "Directory contents:"
              Get-ChildItem
              exit 1
          }

          # Set output variable
          Write-Output "virtual_env=$venvPath" >> $env:GITHUB_OUTPUT

          # Activate virtual environment
          $activateScript = Join-Path $venvPath "Scripts\Activate.ps1"
          if (-not (Test-Path $activateScript)) {
              Write-Error "Activation script not found at: $activateScript"
              Write-Output "Virtual environment contents:"
              Get-ChildItem $venvPath -Recurse
              exit 1
          }

          . $activateScript
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to activate virtual environment"
              Write-Output "Python version: $(python --version)"
              Write-Output "PATH: $env:Path"
              exit 1
          }

          # Verify Python is using the virtual environment
          $pythonPath = (Get-Command python | Select-Object -ExpandProperty Source)
          if (-not $pythonPath.StartsWith($venvPath)) {
              Write-Error "Python is not using the virtual environment"
              Write-Output "Expected Python path to start with: $venvPath"
              Write-Output "Actual Python path: $pythonPath"
              exit 1
          }

          # Upgrade pip
          python -m pip install --upgrade pip
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to upgrade pip"
              exit 1
          }

          # Verify installation
          Write-Output "Verifying Python installation..."
          python --version
          pip list

      - name: Install Node.js packages
        if: inputs.setup_node
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing Node.js packages..."
          npm install -g neovim

      - name: Install Rust
        if: inputs.setup_rust
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Installing Rust..."
          Invoke-WebRequest -Uri https://win.rustup.rs -OutFile rustup-init.exe
          .\rustup-init.exe -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          rustup default stable
          cargo install stylua
