name: Setup Environment

on:
  workflow_call:
    inputs:
      setup_python:
        required: true
        type: boolean
        default: true
      setup_rust:
        required: true
        type: boolean
        default: true
      setup_node:
        required: true
        type: boolean
        default: true
      setup_lua:
        required: true
        type: boolean
        default: true
    outputs:
      virtual_env:
        description: "Path to virtual environment"
        value: ${{ jobs.setup.outputs.virtual_env }}

jobs:
  setup:
    name: Setup Environment
    runs-on: macos-latest
    outputs:
      virtual_env: ${{ steps.venv.outputs.virtual_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        if: inputs.setup_python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Python virtual environment
        if: inputs.setup_python
        id: venv
        run: |
          VENV_PATH="$GITHUB_WORKSPACE/.venv"
          python -m venv "$VENV_PATH"
          echo "virtual_env=$VENV_PATH" >> $GITHUB_OUTPUT
          echo "VIRTUAL_ENV=$VENV_PATH" >> $GITHUB_ENV
          echo "$VENV_PATH/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$VENV_PATH/lib/python3.12/site-packages:$PYTHONPATH" >> $GITHUB_ENV
          echo "PIP_TARGET=$VENV_PATH/lib/python3.12/site-packages" >> $GITHUB_ENV
          echo "PIP_PREFIX=$VENV_PATH" >> $GITHUB_ENV
          source "$VENV_PATH/bin/activate"
          python -m pip install --upgrade pip

      - name: Upload virtual environment
        if: inputs.setup_python
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: .venv
          retention-days: 1

      - name: Set up Rust
        if: inputs.setup_rust
        run: |
          brew install rust rust-analyzer

      - name: Set up Node.js
        if: inputs.setup_node
        run: |
          brew install node

      - name: Set up Lua
        if: inputs.setup_lua
        run: |
          brew install lua luarocks
