name: Setup Environment

on:
  workflow_call:
    inputs:
      setup_python:
        required: true
        type: boolean
        default: true
      setup_rust:
        required: true
        type: boolean
        default: true
      setup_node:
        required: true
        type: boolean
        default: true
      setup_lua:
        required: true
        type: boolean
        default: true
      runner:
        required: true
        type: string
        default: "macos-latest"
    outputs:
      virtual_env:
        description: "Path to virtual environment"
        value: ${{ jobs.setup-environment.outputs.virtual_env }}

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ${{ inputs.runner }}
    outputs:
      virtual_env: ${{ runner.os == 'Windows' && steps.venv-win.outputs.virtual_env || steps.venv-mac.outputs.virtual_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Windows environment
        if: runner.os == 'Windows'
        uses: ./.github/workflows/setup-environment-windows.yml
        with:
          setup_python: ${{ inputs.setup_python }}
          setup_rust: ${{ inputs.setup_rust }}
          setup_node: ${{ inputs.setup_node }}
          setup_lua: ${{ inputs.setup_lua }}

      - name: Set up macOS environment
        if: runner.os == 'macOS'
        uses: ./.github/workflows/setup-environment-macos.yml
        with:
          setup_python: ${{ inputs.setup_python }}
          setup_rust: ${{ inputs.setup_rust }}
          setup_node: ${{ inputs.setup_node }}
          setup_lua: ${{ inputs.setup_lua }}
