name: Setup Windows Environment

on:
  workflow_call:
    inputs:
      setup_python:
        required: true
        type: boolean
        default: true
      setup_rust:
        required: true
        type: boolean
        default: true
      setup_node:
        required: true
        type: boolean
        default: true
      setup_lua:
        required: true
        type: boolean
        default: true
    outputs:
      virtual_env:
        description: "Path to virtual environment"
        value: ${{ jobs.setup-environment.outputs.virtual_env }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    uses: ./.github/workflows/cache-config.yml
    with:
      platform: windows
      setup_python: ${{ inputs.setup_python }}
      setup_rust: ${{ inputs.setup_rust }}
      setup_node: ${{ inputs.setup_node }}

  setup-environment:
    needs: cache
    uses: ./.github/workflows/setup-common.yml
    with:
      platform: windows
      setup_python: ${{ inputs.setup_python }}
      setup_rust: ${{ inputs.setup_rust }}
      setup_node: ${{ inputs.setup_node }}
      setup_lua: ${{ inputs.setup_lua }}

  save-cache:
    needs: [cache, setup-environment]
    if: needs.cache.outputs.choco-cache-hit != 'true'
    runs-on: windows-latest
    steps:
      - name: Save Chocolatey packages
        uses: actions/cache/save@v4
        with:
          path: |
            C:\ProgramData\chocolatey\lib
            C:\ProgramData\chocolatey\bin
            C:\tools
            C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ github.runner.os }}-${{ github.runner.arch }}-choco-${{ hashFiles('infra/packages/*.ps1', 'infra/packages/*.sh') }}
