-- Archived Copilot config.
-- This file is intentionally comment-only so discharged configs stay inert.
-- Restore path:
-- 1. Re-add the Copilot plugin in lua/motleyfesst/lazy.lua.
-- 2. Move the needed mappings/settings into after/plugin/ai/copilot.lua.
--
-- Previous behavior summary:
-- - enabled Copilot on macOS only
-- - disabled the default Tab mapping
-- - set filetype exclusions for Telescope prompt and diff buffers
-- - exposed panel/accept/next/previous/dismiss mappings
